version: "3.4"

services:
  PersonalWebsite:
    image: personalwebsite
    container_name: PersonalWebsite
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
